export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ADD_USER = 'ADD_USER'
export const USERS_LIST = 'USERS_LIST'

export const UNLOCK_PERMISSION = 'UNLOCK_PERMISSION'
export const RECEIVE_PERMISSION = 'RECEIVE_PERMISSION'

export const PLAY_SOUND = 'PLAY_SOUND'
export const RESET_SOUND = 'RESET_SOUND'
export const RECEIVE_SOUND = 'RECEIVE_SOUND'

export const CHECK_USER = 'CHECK_USER'
export const USER_LOGIN = 'USER_LOGIN'
export const ATTEMPT_USER_LOGIN = 'ATTEMPT_USER_LOGIN'

export const UPDATE_USER_ATTEMPT = 'UPDATE_USER_ATTEMPT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
