export const ADD_MESSAGE = 'ADD_MESSAGE'
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED'
export const ADD_USER = 'ADD_USER'

export const SOCKET_OPEN = 'SOCKET_OPEN'
export const CONNECT_TO_SOCKET = 'CONNECT_TO_SOCKET'
export const PLAYER_CONNECTED = 'PLAYER_CONNECTED'
export const PLAYER_UPDATED = 'PLAYER_UPDATED'

export const UNLOCK_PERMISSION = 'UNLOCK_PERMISSION'
export const RECEIVE_PERMISSION = 'RECEIVE_PERMISSION'
export const REHYDRATE_PERMISSIONS = 'REHYDRATE_PERMISSIONS'

export const RECEIVE_TUTORIAL_COMPLETE = 'RECEIVE_TUTORIAL_COMPLETE'
export const UNLOCK_TUTORIAL_COMPLETE = 'UNLOCK_TUTORIAL_COMPLETE'

export const PLAY_SOUND = 'PLAY_SOUND'
export const RESET_SOUND = 'RESET_SOUND'
export const RECEIVE_SOUND = 'RECEIVE_SOUND'

export const CHECK_USER = 'CHECK_USER'
export const USER_LOGIN = 'USER_LOGIN'
export const ATTEMPT_USER_LOGIN = 'ATTEMPT_USER_LOGIN'

export const CHANGE_EDITTING_STATUS = 'CHANGE_EDITTING_STATUS';
export const UPDATE_USER_ATTEMPT = 'UPDATE_USER_ATTEMPT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
